version: '3.9'

services:

  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"



  adminer:
    image: adminer
    restart: always
    ports:
      - "8090:8090"
