INSERT INTO employee (first_name, last_name, email, phone, address, city, state, zip) VALUES
                                                                                          ('John', 'Doe', 'john.doe@example.com', '1234567890', '123 Main St', 'New York', 'NY', '10001'),
                                                                                          ('Jane', 'Smith', 'jane.smith@example.com', '9876543210', '456 Elm St', 'Los Angeles', 'CA', '90001'),
                                                                                          ('Michael', 'Johnson', 'michael.johnson@example.com', '1112223333', '789 Oak St', 'Chicago', 'IL', '60601'),
                                                                                          ('Emily', 'Brown', 'emily.brown@example.com', '2223334444', '101 Pine St', 'Houston', 'TX', '77001'),
                                                                                          ('William', 'Jones', 'william.jones@example.com', '3334445555', '102 Maple St', 'Phoenix', 'AZ', '85001'),
                                                                                          ('Olivia', 'Garcia', 'olivia.garcia@example.com', '4445556666', '103 Cedar St', 'Philadelphia', 'PA', '19101'),
                                                                                          ('James', 'Martinez', 'james.martinez@example.com', '5556667777', '104 Birch St', 'San Antonio', 'TX', '78201'),
                                                                                          ('Sophia', 'Rodriguez', 'sophia.rodriguez@example.com', '6667778888', '105 Walnut St', 'San Diego', 'CA', '92101'),
                                                                                          ('Benjamin', 'Lee', 'benjamin.lee@example.com', '7778889999', '106 Aspen St', 'Dallas', 'TX', '75201'),
                                                                                          ('Amelia', 'Clark', 'amelia.clark@example.com', '8889990000', '107 Spruce St', 'San Jose', 'CA', '95101'),
                                                                                          ('Alexander', 'Harris', 'alexander.harris@example.com', '9990001111', '108 Redwood St', 'Austin', 'TX', '73301'),
                                                                                          ('Charlotte', 'Lewis', 'charlotte.lewis@example.com', '0001112222', '109 Cypress St', 'Jacksonville', 'FL', '32099'),
                                                                                          ('Henry', 'Walker', 'henry.walker@example.com', '1112223333', '110 Willow St', 'San Francisco', 'CA', '94101'),
                                                                                          ('Ava', 'Hall', 'ava.hall@example.com', '2223334444', '111 Palm St', 'Columbus', 'OH', '43085'),
                                                                                          ('Elijah', 'Allen', 'elijah.allen@example.com', '3334445555', '112 Fir St', 'Fort Worth', 'TX', '76101'),
                                                                                          ('Isabella', 'Young', 'isabella.young@example.com', '4445556666', '113 Hickory St', 'Indianapolis', 'IN', '46201'),
                                                                                          ('Mason', 'Hernandez', 'mason.hernandez@example.com', '5556667777', '114 Dogwood St', 'Charlotte', 'NC', '28201'),
                                                                                          ('Mia', 'King', 'mia.king@example.com', '6667778888', '115 Magnolia St', 'Seattle', 'WA', '98101'),
                                                                                          ('Logan', 'Wright', 'logan.wright@example.com', '7778889999', '116 Chestnut St', 'Denver', 'CO', '80201'),
                                                                                          ('Harper', 'Lopez', 'harper.lopez@example.com', '8889990000', '117 Sequoia St', 'Washington', 'DC', '20001'),
                                                                                          ('Ethan', 'Hill', 'ethan.hill@example.com', '9990001111', '118 Acacia St', 'Boston', 'MA', '02101'),
                                                                                          ('Abigail', 'Scott', 'abigail.scott@example.com', '0001112222', '119 Sycamore St', 'El Paso', 'TX', '79901'),
                                                                                          ('Lucas', 'Green', 'lucas.green@example.com', '1112223333', '120 Cherry St', 'Detroit', 'MI', '48201'),
                                                                                          ('Ella', 'Adams', 'ella.adams@example.com', '2223334444', '121 Cottonwood St', 'Nashville', 'TN', '37201'),
                                                                                          ('Noah', 'Baker', 'noah.baker@example.com', '3334445555', '122 Poplar St', 'Oklahoma City', 'OK', '73101'),
                                                                                          ('Avery', 'Nelson', 'avery.nelson@example.com', '4445556666', '123 Laurel St', 'Las Vegas', 'NV', '89101'),
                                                                                          ('Carter', 'Carter', 'carter.carter@example.com', '5556667777', '124 Holly St', 'Portland', 'OR', '97201'),
                                                                                          ('Aria', 'Mitchell', 'aria.mitchell@example.com', '6667778888', '125 Beech St', 'Memphis', 'TN', '38101'),
                                                                                          ('Jacob', 'Perez', 'jacob.perez@example.com', '7778889999', '126 Pinecone St', 'Baltimore', 'MD', '21201'),
                                                                                          ('Grace', 'Roberts', 'grace.roberts@example.com', '8889990000', '127 Maplewood St', 'Louisville', 'KY', '40201');
